<a href="https://colab.research.google.com/github/abdullah-forge/Pandas/blob/main/Pandas_practise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
coffee = pd.read_csv("coffee_sales.csv")
coffee

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2,450,20
1,1002,Sara,Karachi,Espresso,Medium,1,350,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,25
4,1005,Hassan,Multan,Americano,Large,4,400,40
5,1006,Zainab,Lahore,Latte,Medium,1,450,10
6,1007,Usman,Karachi,Espresso,Small,5,350,50
7,1008,Maryam,Islamabad,Flat White,Large,2,600,30
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500,20
9,1010,Fatima,Quetta,Mocha,Medium,2,550,25

In [8]:
coffee.head()

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2,450,20
1,1002,Sara,Karachi,Espresso,Medium,1,350,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,25
4,1005,Hassan,Multan,Americano,Large,4,400,40

In [9]:
coffee.columns

Index(['Order_ID', 'Customer', 'City', 'Coffee_Type', 'Size', 'Quantity',
       'Price_Per_Cup', 'Discount'],
      dtype='object')

In [11]:
# droping column
coffee = coffee.drop("Discount", axis=1)

KeyError: "['Discount'] not found in axis"

In [12]:
coffee.head()

   Order_ID Customer        City Coffee_Type    Size  Quantity  Price_Per_Cup
0      1001      Ali      Lahore       Latte   Small         2            450
1      1002     Sara     Karachi    Espresso  Medium         1            350
2      1003    Ahmed   Islamabad  Cappuccino   Large         3            500
3      1004   Ayesha  Faisalabad       Mocha  Medium         2            550
4      1005   Hassan      Multan   Americano   Large         4            400

In [15]:
# rename column
coffee = coffee.rename(columns={
    "Price_Per_Cup" : "Price"
})

In [16]:
coffee.head()

   Order_ID Customer        City Coffee_Type    Size  Quantity  Price
0      1001      Ali      Lahore       Latte   Small         2    450
1      1002     Sara     Karachi    Espresso  Medium         1    350
2      1003    Ahmed   Islamabad  Cappuccino   Large         3    500
3      1004   Ayesha  Faisalabad       Mocha  Medium         2    550
4      1005   Hassan      Multan   Americano   Large         4    400

In [17]:
# creating new column and column multiplication
coffee["Total"] = coffee["Quantity"] * coffee["Price"]

In [18]:
coffee.head()

   Order_ID Customer        City Coffee_Type    Size  Quantity  Price  Total
0      1001      Ali      Lahore       Latte   Small         2    450    900
1      1002     Sara     Karachi    Espresso  Medium         1    350    350
2      1003    Ahmed   Islamabad  Cappuccino   Large         3    500   1500
3      1004   Ayesha  Faisalabad       Mocha  Medium         2    550   1100
4      1005   Hassan      Multan   Americano   Large         4    400   1600

In [20]:
#save specific column
customer_bill = coffee[["Customer", "Total"]]

In [21]:
customer_bill

  Customer  Total
0      Ali    900
1     Sara    350
2    Ahmed   1500
3   Ayesha   1100
4   Hassan   1600
5   Zainab    450
6    Usman   1750
7   Maryam   1200
8    Bilal   1500
9   Fatima   1100

In [22]:
customer_bill.to_csv("customer>bill.csv", index=False)

In [23]:
suppliers = pd.read_csv("coffee_suppliers.csv")

In [24]:
suppliers.head()

  Supplier_ID Coffee_Type   Supplier_Name   Country
0        S101       Latte    Bean Masters    Brazil
1        S102    Espresso      Black Gold  Colombia
2        S103  Cappuccino  Mountain Beans  Ethiopia
3        S104       Mocha   Premium Roast     Kenya
4        S105   Americano    Coffee World   Vietnam

In [26]:
merge = pd.merge(
    coffee,suppliers, on="Coffee_Type"
)

In [27]:
merge

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price,Total,Supplier_ID,Supplier_Name,Country
0,1001,Ali,Lahore,Latte,Small,2,450,900,S101,Bean Masters,Brazil
1,1002,Sara,Karachi,Espresso,Medium,1,350,350,S102,Black Gold,Colombia
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,1500,S103,Mountain Beans,Ethiopia
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,1100,S104,Premium Roast,Kenya
4,1005,Hassan,Multan,Americano,Large,4,400,1600,S105,Coffee World,Vietnam
5,1006,Zainab,Lahore,Latte,Medium,1,450,450,S101,Bean Masters,Brazil
6,1007,Usman,Karachi,Espresso,Small,5,350,1750,S102,Black Gold,Colombia
7,1008,Maryam,Islamabad,Flat White,Large,2,600,1200,S106,Elite Coffee,Indonesia
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500,1500,S103,Mountain Beans,Ethiopia
9,1010,Fatima,Quetta,Mocha,Medium,2,550,1100,S104,Premium Roast,Kenya

In [28]:
branches = pd.read_csv("coffee_branches.csv")

In [29]:
coffee_branches = pd.merge(
    coffee, branches, on="City"
)

In [30]:
coffee_branches

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price,Total,Branch_ID,Manager
0,1001,Ali,Lahore,Latte,Small,2,450,900,B01,Kamran
1,1002,Sara,Karachi,Espresso,Medium,1,350,350,B02,Hina
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,1500,B03,Usama
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,1100,B04,Nida
4,1005,Hassan,Multan,Americano,Large,4,400,1600,B05,Hamza
5,1006,Zainab,Lahore,Latte,Medium,1,450,450,B01,Kamran
6,1007,Usman,Karachi,Espresso,Small,5,350,1750,B02,Hina
7,1008,Maryam,Islamabad,Flat White,Large,2,600,1200,B03,Usama
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500,1500,B06,Saqib
9,1010,Fatima,Quetta,Mocha,Medium,2,550,1100,B07,Amna

In [32]:
new_orders = pd.read_csv("new_orders.csv")

In [34]:
#concatenating
all_orders = pd.concat([coffee, new_orders], ignore_index = True)

In [35]:
all_orders

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price,Total,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2,450.0,900.0,NaN,NaN
1,1002,Sara,Karachi,Espresso,Medium,1,350.0,350.0,NaN,NaN
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500.0,1500.0,NaN,NaN
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550.0,1100.0,NaN,NaN
4,1005,Hassan,Multan,Americano,Large,4,400.0,1600.0,NaN,NaN
5,1006,Zainab,Lahore,Latte,Medium,1,450.0,450.0,NaN,NaN
6,1007,Usman,Karachi,Espresso,Small,5,350.0,1750.0,NaN,NaN
7,1008,Maryam,Islamabad,Flat White,Large,2,600.0,1200.0,NaN,NaN
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500.0,1500.0,NaN,NaN
9,1010,Fatima,Quetta,Mocha,Medium,2,550.0,1100.0,NaN,NaN
10,1011,Noor,Lahore,Latte,Large,2,NaN,NaN,450.0,20.0
11,1012,Saad,Karachi,Mocha,Small,1,NaN,NaN,550.0,10.0
12,1013,Eman,Islamabad,Espresso,Medium,3,NaN,NaN,350.0,30.0

In [36]:
# combine
combined = coffee.join(branches.set_index("City"), on="City")

In [37]:
combined

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price,Total,Branch_ID,Manager
0,1001,Ali,Lahore,Latte,Small,2,450,900,B01,Kamran
1,1002,Sara,Karachi,Espresso,Medium,1,350,350,B02,Hina
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,1500,B03,Usama
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,1100,B04,Nida
4,1005,Hassan,Multan,Americano,Large,4,400,1600,B05,Hamza
5,1006,Zainab,Lahore,Latte,Medium,1,450,450,B01,Kamran
6,1007,Usman,Karachi,Espresso,Small,5,350,1750,B02,Hina
7,1008,Maryam,Islamabad,Flat White,Large,2,600,1200,B03,Usama
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500,1500,B06,Saqib
9,1010,Fatima,Quetta,Mocha,Medium,2,550,1100,B07,Amna

In [38]:
combined.to_csv("final_coffee_data.csv",index=False)

In [39]:
quantity = coffee.loc[0,"Quantity"]
if quantity > 2:
  print("Large Order")
else:
  print("Small order")

Small order

In [41]:
#using for loop
for qty in coffee["Quantity"]:
  if qty > 3:
    print("Bulk Order")
  else:
    print("Small Order")

Small Order
Small Order
Small Order
Small Order
Bulk Order
Small Order
Bulk Order
Small Order
Small Order
Small Order

In [42]:
#creating new column using if else
order_type = []
for qty in coffee["Quantity"]:
  if qty > 3:
    order_type.append("Bulk Order")
  else:
    order_type.append("Small Order")

In [43]:
coffee["Order Type"] = order_type

In [44]:
coffee

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price,Total,Order Type
0,1001,Ali,Lahore,Latte,Small,2,450,900,Small Order
1,1002,Sara,Karachi,Espresso,Medium,1,350,350,Small Order
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,1500,Small Order
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,1100,Small Order
4,1005,Hassan,Multan,Americano,Large,4,400,1600,Bulk Order
5,1006,Zainab,Lahore,Latte,Medium,1,450,450,Small Order
6,1007,Usman,Karachi,Espresso,Small,5,350,1750,Bulk Order
7,1008,Maryam,Islamabad,Flat White,Large,2,600,1200,Small Order
8,1009,Bilal,Peshawar,Cappuccino,Small,3,500,1500,Small Order
9,1010,Fatima,Quetta,Mocha,Medium,2,550,1100,Small Order