<a href="https://colab.research.google.com/github/abdullah-forge/Pandas/blob/main/practise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
coffee = pd.read_csv("coffee_sales.csv")

In [4]:
coffee.head()

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2,450,20
1,1002,Sara,Karachi,Espresso,Medium,1,350,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,3,500,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2,550,25
4,1005,Hassan,Multan,Americano,Large,4,400,40

In [5]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       10 non-null     int64
 1   Customer       10 non-null     object
 2   City           10 non-null     object
 3   Coffee_Type    10 non-null     object
 4   Size           10 non-null     object
 5   Quantity       10 non-null     int64
 6   Price_Per_Cup  10 non-null     int64
 7   Discount       10 non-null     int64
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

In [7]:
coffee.shape

(10, 8)

In [9]:
coffee.describe()

         Order_ID   Quantity  Price_Per_Cup   Discount
count    10.00000  10.000000      10.000000  10.000000
mean   1005.50000   2.500000     470.000000  25.000000
std       3.02765   1.269296      85.634884  14.142136
min    1001.00000   1.000000     350.000000   0.000000
25%    1003.25000   2.000000     412.500000  20.000000
50%    1005.50000   2.000000     475.000000  25.000000
75%    1007.75000   3.000000     537.500000  30.000000
max    1010.00000   5.000000     600.000000  50.000000

In [10]:
coffee.columns

Index(['Order_ID', 'Customer', 'City', 'Coffee_Type', 'Size', 'Quantity',
       'Price_Per_Cup', 'Discount'],
      dtype='object')

In [12]:
#Create Some Null Values
coffee.loc[2,"Quantity"] = None
coffee.loc[5,"Price_Per_Cup"] = None
coffee.loc[7, "City"] = None

In [13]:
coffee

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2.0,450.0,20
1,1002,Sara,Karachi,Espresso,Medium,1.0,350.0,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,NaN,500.0,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2.0,550.0,25
4,1005,Hassan,Multan,Americano,Large,4.0,400.0,40
5,1006,Zainab,Lahore,Latte,Medium,1.0,NaN,10
6,1007,Usman,Karachi,Espresso,Small,5.0,350.0,50
7,1008,Maryam,None,Flat White,Large,2.0,600.0,30
8,1009,Bilal,Peshawar,Cappuccino,Small,3.0,500.0,20
9,1010,Fatima,Quetta,Mocha,Medium,2.0,550.0,25

In [14]:
#Handling Null Values
coffee.isna()
coffee.isna().sum()

Order_ID         0
Customer         0
City             1
Coffee_Type      0
Size             0
Quantity         1
Price_Per_Cup    1
Discount         0
dtype: int64

In [15]:
coffee.notna()

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,False,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,False,True
6,True,True,True,True,True,True,True,True
7,True,True,False,True,True,True,True,True
8,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True

In [17]:
coffee.fillna(0)

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2.0,450.0,20
1,1002,Sara,Karachi,Espresso,Medium,1.0,350.0,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,0.0,500.0,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2.0,550.0,25
4,1005,Hassan,Multan,Americano,Large,4.0,400.0,40
5,1006,Zainab,Lahore,Latte,Medium,1.0,0.0,10
6,1007,Usman,Karachi,Espresso,Small,5.0,350.0,50
7,1008,Maryam,0,Flat White,Large,2.0,600.0,30
8,1009,Bilal,Peshawar,Cappuccino,Small,3.0,500.0,20
9,1010,Fatima,Quetta,Mocha,Medium,2.0,550.0,25

In [18]:
coffee["Quantity"] = coffee["Quantity"].fillna(coffee["Quantity"].mean())

In [19]:
coffee.dropna()

,Order_ID,Customer,City,Coffee_Type,Size,Quantity,Price_Per_Cup,Discount
0,1001,Ali,Lahore,Latte,Small,2.000000,450.0,20
1,1002,Sara,Karachi,Espresso,Medium,1.000000,350.0,0
2,1003,Ahmed,Islamabad,Cappuccino,Large,2.444444,500.0,30
3,1004,Ayesha,Faisalabad,Mocha,Medium,2.000000,550.0,25
4,1005,Hassan,Multan,Americano,Large,4.000000,400.0,40
6,1007,Usman,Karachi,Espresso,Small,5.000000,350.0,50
8,1009,Bilal,Peshawar,Cappuccino,Small,3.000000,500.0,20
9,1010,Fatima,Quetta,Mocha,Medium,2.000000,550.0,25

In [20]:
coffee["Quantity"] = coffee["Quantity"].interpolate()

In [21]:
coffee["Quantity"].sum()

np.float64(24.444444444444443)

In [22]:
coffee["Price_Per_Cup"].mean()

np.float64(472.22222222222223)

In [23]:
coffee["Price_Per_Cup"].max()

600.0

In [24]:
coffee["Price_Per_Cup"].min()

350.0

In [27]:
coffee["Coffee_Type"].value_counts()

Coffee_Type
Latte         2
Espresso      2
Cappuccino    2
Mocha         2
Americano     1
Flat White    1
Name: count, dtype: int64

In [28]:
coffee["City"].value_counts()

City
Lahore        2
Karachi       2
Islamabad     1
Faisalabad    1
Multan        1
Peshawar      1
Quetta        1
Name: count, dtype: int64

In [29]:
coffee.groupby("Coffee_Type")["Quantity"].sum()

Coffee_Type
Americano     4.000000
Cappuccino    5.444444
Espresso      6.000000
Flat White    2.000000
Latte         3.000000
Mocha         4.000000
Name: Quantity, dtype: float64

In [31]:
coffee.groupby("Coffee_Type")["Price_Per_Cup"].mean()

Coffee_Type
Americano     400.0
Cappuccino    500.0
Espresso      350.0
Flat White    600.0
Latte         450.0
Mocha         550.0
Name: Price_Per_Cup, dtype: float64

In [32]:
coffee.groupby("Coffee_Type").agg({
    "Quantity":"sum",
    "Price_Per_Cup":"mean"
})

             Quantity  Price_Per_Cup
Coffee_Type
Americano    4.000000          400.0
Cappuccino   5.444444          500.0
Espresso     6.000000          350.0
Flat White   2.000000          600.0
Latte        3.000000          450.0
Mocha        4.000000          550.0

In [33]:
pd.pivot_table(
    coffee,
    values="Quantity",
    index="Coffee_Type",
    columns="City",
    aggfunc="sum"
)

City         Faisalabad  Islamabad  Karachi  Lahore  Multan  Peshawar  Quetta
Coffee_Type
Americano           NaN        NaN      NaN     NaN     4.0       NaN     NaN
Cappuccino          NaN   2.444444      NaN     NaN     NaN       3.0     NaN
Espresso            NaN        NaN      6.0     NaN     NaN       NaN     NaN
Latte               NaN        NaN      NaN     3.0     NaN       NaN     NaN
Mocha               2.0        NaN      NaN     NaN     NaN       NaN     2.0

In [34]:
coffee["Prevous_Quantity"] = coffee["Quantity"].shift(1)

In [35]:
coffee["Next_Quantity"] = coffee["Quantity"].shift(-1)

In [36]:
coffee["Rank"] = coffee["Price_Per_Cup"].rank()

In [37]:
coffee["Rank"] = coffee["Price_Per_Cup"].rank(ascending=False)

In [38]:
coffee["Rolling_Average"] = coffee["Quantity"].rolling(3).mean()

In [39]:
coffee["Rolling_sum"] = coffee["Quantity"].rolling(3).sum()

In [40]:
coffee["Running_Total"] = coffee["Quantity"].cumsum()

In [42]:
group = coffee.groupby("Coffee_Type").sum()

In [43]:
group.reset_index()

,Coffee_Type,Order_ID,Customer,City,Size,Quantity,Price_Per_Cup,Discount,Prevous_Quantity,Next_Quantity,Rank,Rolling_Average,Rolling_sum,Running_Total
0,Americano,1005,Hassan,Multan,Large,4.000000,400.0,40,2.000000,1.000000,7.0,2.814815,8.444444,11.444444
1,Cappuccino,2012,AhmedBilal,IslamabadPeshawar,LargeSmall,5.444444,1000.0,50,3.000000,4.000000,9.0,5.148148,15.444444,27.888889
2,Espresso,2009,SaraUsman,KarachiKarachi,MediumSmall,6.000000,700.0,50,3.000000,4.444444,17.0,3.333333,10.000000,20.444444
3,Flat White,1008,Maryam,0,Large,2.000000,600.0,30,5.000000,3.000000,1.0,2.666667,8.000000,19.444444
4,Latte,2007,AliZainab,LahoreLahore,SmallMedium,3.000000,450.0,30,4.000000,6.000000,6.0,2.333333,7.000000,14.444444
5,Mocha,2014,AyeshaFatima,FaisalabadQuetta,MediumMedium,4.000000,1100.0,50,5.444444,4.000000,5.0,4.148148,12.444444,31.888889

In [44]:
coffee.to_csv("Updated_Coffee_Data.csv", index=False)